# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161117174642 on 2016-11-20 04:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/processes'))),
                ('email', models.EmailField(max_length=254)),
                ('calibration', models.CharField(max_length=255)),
            ],
        ),
    ]
