# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161117174642 on 2016-11-20 06:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cal_file',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/processes')),
        ),
    ]
